### PR TITLE
(REMOVE) Outdated Components

### PR DESCRIPTION
**Pull request by RichardMcCarty1**

### CODE REVIEW

**Comment by bowring** [comment]
@RichardMcCarty1 -  This breaks Services.war so that this does not work from our CURL_EXPERIMENT folder:
```java
curl -F "prawnFile=@836_1_2016_Nov_28_09.50.xml.zip" -F "taskFile=@SquidTask_Z6266 = 11pk Perm1.SB.xls" 0.0.0.0:8080/squidReporting -F "useSBM=true" -F "userLinFits=false" -F "refMatFilter=6266" -F "concRefMatFilter=6266" -v  > reports2.zip
```

and returns a 404 for squidReporting service

**Comment by bowring** [comment]
@RichardMcCarty1 - let's have a meeting about this as well as there are other oddities in this PR.

**Comment by RichardMcCarty1** [comment]
In regards to the 404, I believe you have to reference the tomcat endpoint through /Services because it is a subsection of that path, so something like 
```curl -F "prawnFile=@836_1_2016_Nov_28_09.50.xml.zip" -F "taskFile=@SquidTask_Z6266 = 11pk Perm1.SB.xls" 0.0.0.0:8080/Services/squidReporting -F "useSBM=true" -F "userLinFits=false" -F "refMatFilter=6266" -F "concRefMatFilter=6266" -v  > reports2.zip```

**Comment by bowring** [comment]
You are correct and you managed to fix a bug I had forgotten about, which was that the call without Services worked on localhost, but Services/squidReporting was needed to the remote server - now they are identical as should be.

**Comment by bowring** [comment]
SquidInkStartupServlet has unused imports throwing errors, should only have:
```java
import org.apache.commons.io.IOUtils;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Stack;
```

**Review by bowring — CHANGES_REQUESTED** [review]
probably ought to leave in the snapshots enabling in pom

SquidInkStartupServlet has unused imports throwing errors, should only have:
```java
import org.apache.commons.io.IOUtils;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Stack;
```

**Comment by RichardMcCarty1** [comment]
@bowring Pushed up a change to remove all the unused imports, I'm keeping 
```
import java.lang.Runtime;
import java.lang.Process
```

as they're used to spawn the container, Process isn't currently used beyond creating an instance via runtime exec but it allows us to read out the containers out if that becomes something that needs to happen, i.e. to know when the container has finished spawning to redirect the user.

**Review by bowring — APPROVED** [review]

**Pull request merged**
